//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Models.DataBase.Migrations
{
    public partial class UpdateShelf : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ShelfBook_Shelves_ShelfId",
                table: "ShelfBook");

            migrationBuilder.AddForeignKey(
                name: "FK_ShelfBook_Shelves_ShelfId",
                table: "ShelfBook",
                column: "ShelfId",
                principalTable: "Shelves",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ShelfBook_Shelves_ShelfId",
                table: "ShelfBook");

            migrationBuilder.AddForeignKey(
                name: "FK_ShelfBook_Shelves_ShelfId",
                table: "ShelfBook",
                column: "ShelfId",
                principalTable: "Shelves",
                principalColumn: "Id");
        }
    }
}
