//<auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Models.DataBase.Migrations
{
    public partial class UpdateModels : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ReadSection_Histories_HistoryBookId",
                table: "ReadSection");

            migrationBuilder.AddForeignKey(
                name: "FK_ReadSection_Histories_HistoryBookId",
                table: "ReadSection",
                column: "HistoryBookId",
                principalTable: "Histories",
                principalColumn: "BookId",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ReadSection_Histories_HistoryBookId",
                table: "ReadSection");

            migrationBuilder.AddForeignKey(
                name: "FK_ReadSection_Histories_HistoryBookId",
                table: "ReadSection",
                column: "HistoryBookId",
                principalTable: "Histories",
                principalColumn: "BookId");
        }
    }
}
